// Fallback mock data for when the backend API is unavailable (e.g., Supabase paused)

export const MOCK_FEED_ARTICLES = [
  {
    id: 'article-fixed-001',
    title: '느린 사고가 만드는 깊이 있는 디자인',
    platform: 'Brunch',
    platformIcon: '📝',
    topics: ['디자인 철학', '인지심리'],
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1546098073-4d874a1c59f8?w=400&h=300&fit=crop',
    author: '김지윤',
    excerpt: '빠른 것이 좋은 것이라는 가정을 뒤집는 느린 디자인의 세계',
    readProgress: 35,
  },
  {
    id: 'article-fixed-002',
    title: '주의력의 경제학: 디지털 시대의 집중력',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['행동경제학', '인지심리'],
    readTime: 12,
    thumbnail: 'https://images.unsplash.com/photo-1639414839192-0562f4065ffd?w=400&h=300&fit=crop',
    author: '이준호',
    excerpt: '유한한 자원인 주의력을 어떻게 분배할 것인가',
  },
  {
    id: 'article-fixed-003',
    title: '좋은 질문이 좋은 답보다 중요한 이유',
    platform: 'Velog',
    platformIcon: '💻',
    topics: ['비판적 사고', '학습 이론'],
    readTime: 7,
    thumbnail: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=300&fit=crop',
    author: '박서연',
    excerpt: '질문의 기술이 사고의 깊이를 결정한다',
    readProgress: 62,
  },
  {
    id: 'article-fixed-004',
    title: '시스템 1과 시스템 2 사이에서',
    platform: '브런치',
    platformIcon: '📝',
    topics: ['인지심리', '제품 사고'],
    readTime: 10,
    thumbnail: 'https://images.unsplash.com/photo-1729105140273-b5e886a4f999?w=400&h=300&fit=crop',
    author: '정민수',
    excerpt: '카너먼의 이중과정이론으로 보는 사용자 행동',
  },
  {
    id: 'article-fixed-005',
    title: '창의성은 제약에서 시작된다',
    platform: 'ㅍㅍㅅㅅ',
    platformIcon: '📰',
    topics: ['창의성', '디자인 철학'],
    readTime: 6,
    thumbnail: 'https://images.unsplash.com/photo-1656877280226-ebf9ea8b1303?w=400&h=300&fit=crop',
    author: '최하은',
    excerpt: '한계가 오히려 더 나은 결과를 이끄는 이유',
  },
  {
    id: 'article-fixed-006',
    title: '읽기와 쓰기, 그리고 생각하기',
    platform: 'Brunch',
    platformIcon: '📝',
    topics: ['글쓰기', '학습 이론'],
    readTime: 9,
    thumbnail: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400&h=300&fit=crop',
    author: '한소희',
    excerpt: '읽는 행위가 어떻게 사고를 형성하는가',
  },
  {
    id: 'article-fixed-007',
    title: '인지 부하를 줄이는 인터페이스 디자인',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['UX 리서치', '인지심리'],
    readTime: 11,
    thumbnail: 'https://images.unsplash.com/photo-1766250533363-01b974b2ba32?w=400&h=300&fit=crop',
    author: '오태현',
    excerpt: 'Miller의 법칙부터 Hick의 법칙까지',
  },
  {
    id: 'article-fixed-008',
    title: '복잡계와 시스템 사고의 즐거움',
    platform: 'Velog',
    platformIcon: '💻',
    topics: ['시스템 사고', '비판적 사고'],
    readTime: 14,
    thumbnail: 'https://images.unsplash.com/photo-1670182088755-48d7171e5e44?w=400&h=300&fit=crop',
    author: '류지원',
    excerpt: '나비효과에서 피드백 루프까지, 세상을 보는 새로운 렌즈',
  },
  {
    id: 'article-fixed-009',
    title: '사용자를 이해한다는 것의 의미',
    platform: '브런치',
    platformIcon: '📝',
    topics: ['UX 리서치', '제품 사고'],
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1545875589-7bacdcc464ae?w=400&h=300&fit=crop',
    author: '강다인',
    excerpt: '데이터 너머의 공감, 리서치의 본질',
  },
  {
    id: 'article-fixed-010',
    title: '넛지 디자인: 선택을 설계하는 기술',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['행동경제학', '제품 사고'],
    readTime: 10,
    thumbnail: 'https://images.unsplash.com/photo-1546098073-4d874a1c59f8?w=400&h=300&fit=crop',
    author: '윤서준',
    excerpt: '탈러와 선스타인이 말하는 자유주의적 개입주의',
  },
  {
    id: 'article-fixed-011',
    title: '미니멀리즘과 본질적 사고',
    platform: 'Brunch',
    platformIcon: '📝',
    topics: ['디자인 철학', '창의성'],
    readTime: 7,
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    author: '송민지',
    excerpt: '더하기보다 빼기의 미학',
  },
  {
    id: 'article-fixed-012',
    title: '메타인지: 생각에 대한 생각',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['학습 이론', '인지심리'],
    readTime: 9,
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop',
    author: '김태영',
    excerpt: '어떻게 더 나은 학습자가 될 것인가',
  },
  {
    id: 'article-fixed-013',
    title: '정보의 숲에서 길을 잃지 않는 법',
    platform: 'Velog',
    platformIcon: '💻',
    topics: ['비판적 사고', '시스템 사고'],
    readTime: 11,
    thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
    author: '이현우',
    excerpt: '정보 과부하 시대의 생존 전략',
  },
  {
    id: 'article-fixed-014',
    title: '루틴의 힘: 습관이 만드는 변화',
    platform: '브런치',
    platformIcon: '📝',
    topics: ['행동경제학', '학습 이론'],
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=300&fit=crop',
    author: '정수빈',
    excerpt: '작은 습관이 만드는 큰 차이',
  },
  {
    id: 'article-fixed-015',
    title: '대화의 기술: 듣기의 중요성',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['UX 리서치', '비판적 사고'],
    readTime: 6,
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop',
    author: '박지현',
    excerpt: '공감적 경청이 이끄는 깊은 이해',
  },
];

const now = new Date();

export const MOCK_SAVED_ARTICLES = [
  {
    id: 'saved-001',
    title: '느린 사고가 만드는 깊이 있는 디자인',
    platform: 'Brunch',
    platformIcon: '📝',
    topics: ['디자인 철학', '인지심리'],
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1546098073-4d874a1c59f8?w=400&h=300&fit=crop',
    author: '김지윤',
    excerpt: '빠른 것이 좋은 것이라는 가정을 뒤집는 느린 디자인의 세계',
    savedAt: new Date(now.getTime() - 2 * 86400000).toISOString(),
  },
  {
    id: 'saved-002',
    title: '주의력의 경제학: 디지털 시대의 집중력',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['행동경제학', '인지심리'],
    readTime: 12,
    thumbnail: 'https://images.unsplash.com/photo-1639414839192-0562f4065ffd?w=400&h=300&fit=crop',
    author: '이준호',
    excerpt: '유한한 자원인 주의력을 어떻게 분배할 것인가',
    savedAt: new Date(now.getTime() - 4 * 86400000).toISOString(),
  },
  {
    id: 'saved-003',
    title: '창의성은 제약에서 시작된다',
    platform: 'ㅍㅍㅅㅅ',
    platformIcon: '📰',
    topics: ['창의성', '디자인 철학'],
    readTime: 6,
    thumbnail: 'https://images.unsplash.com/photo-1656877280226-ebf9ea8b1303?w=400&h=300&fit=crop',
    author: '최하은',
    excerpt: '한계가 오히려 더 나은 결과를 이끄는 이유',
    savedAt: new Date(now.getTime() - 6 * 86400000).toISOString(),
  },
  {
    id: 'saved-004',
    title: '인지 부하를 줄이는 인터페이스 디자인',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['UX 리서치', '인지심리'],
    readTime: 11,
    thumbnail: 'https://images.unsplash.com/photo-1766250533363-01b974b2ba32?w=400&h=300&fit=crop',
    author: '오태현',
    excerpt: 'Miller의 법칙부터 Hick의 법칙까지',
    savedAt: new Date(now.getTime() - 9 * 86400000).toISOString(),
  },
  {
    id: 'saved-005',
    title: '시스템 1과 시스템 2 사이에서',
    platform: '브런치',
    platformIcon: '📝',
    topics: ['인지심리', '제품 사고'],
    readTime: 10,
    thumbnail: 'https://images.unsplash.com/photo-1729105140273-b5e886a4f999?w=400&h=300&fit=crop',
    author: '정민수',
    excerpt: '카너먼의 이중과정이론으로 보는 사용자 행동',
    savedAt: new Date(now.getTime() - 12 * 86400000).toISOString(),
  },
  {
    id: 'saved-006',
    title: '좋은 질문이 좋은 답보다 중요한 이유',
    platform: 'Velog',
    platformIcon: '💻',
    topics: ['비판적 사고', '학습 이론'],
    readTime: 7,
    thumbnail: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=300&fit=crop',
    author: '박서연',
    excerpt: '질문의 기술이 사고의 깊이를 결정한다',
    savedAt: new Date(now.getTime() - 15 * 86400000).toISOString(),
  },
  {
    id: 'saved-007',
    title: '복잡계와 시스템 사고의 즐거움',
    platform: 'Velog',
    platformIcon: '💻',
    topics: ['시스템 사고', '비판적 사고'],
    readTime: 14,
    thumbnail: 'https://images.unsplash.com/photo-1670182088755-48d7171e5e44?w=400&h=300&fit=crop',
    author: '류지원',
    excerpt: '나비효과에서 피드백 루프까지, 세상을 보는 새로운 렌즈',
    savedAt: new Date(now.getTime() - 18 * 86400000).toISOString(),
  },
  {
    id: 'saved-008',
    title: '메타인지: 생각에 대한 생각',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['학습 이론', '인지심리'],
    readTime: 9,
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop',
    author: '김태영',
    excerpt: '어떻게 더 나은 학습자가 될 것인가',
    savedAt: new Date(now.getTime() - 21 * 86400000).toISOString(),
  },
  {
    id: 'saved-009',
    title: '넛지 디자인: 선택을 설계하는 기술',
    platform: 'Medium',
    platformIcon: '✍️',
    topics: ['행동경제학', '제품 사고'],
    readTime: 10,
    thumbnail: 'https://images.unsplash.com/photo-1546098073-4d874a1c59f8?w=400&h=300&fit=crop',
    author: '윤서준',
    excerpt: '탈러와 선스타인이 말하는 자유주의적 개입주의',
    savedAt: new Date(now.getTime() - 25 * 86400000).toISOString(),
  },
  {
    id: 'saved-010',
    title: '사용자를 이해한다는 것의 의미',
    platform: '브런치',
    platformIcon: '📝',
    topics: ['UX 리서치', '제품 사고'],
    readTime: 8,
    thumbnail: 'https://images.unsplash.com/photo-1545875589-7bacdcc464ae?w=400&h=300&fit=crop',
    author: '강다인',
    excerpt: '데이터 너머의 공감, 리서치의 본질',
    savedAt: new Date(now.getTime() - 30 * 86400000).toISOString(),
  },
];

export const MOCK_CONNECTIONS = [
  {
    userId: 'conn-user-001',
    displayName: '사려깊은독자',
    sharedTopics: ['디자인 철학', '인지심리', 'UX 리서치'],
    overlapPercentage: 78,
    lastReadInCommon: '느린 사고가 만드는 깊',
    connectedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    userId: 'conn-user-002',
    displayName: '생각하는사람',
    sharedTopics: ['시스템 사고', '비판적 사고'],
    overlapPercentage: 65,
    lastReadInCommon: '주의력의 경제학',
    connectedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    userId: 'conn-user-003',
    displayName: '조용한탐구자',
    sharedTopics: ['글쓰기', '창의성', '학습 이론'],
    overlapPercentage: 58,
    lastReadInCommon: '창의성은 제약에서 시작된다',
    connectedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

export const MOCK_RECOMMENDATION = {
  userId: 'rec-user-001',
  displayName: '심층독서가',
  bio: '깊이 있는 독서를 사랑합니다',
  sharedTopics: ['디자인 철학', '행동경제학', '인지심리'],
  overlapPercentage: 72,
  recentReads: ['느린 사고가 만드는 깊이 있는 디자인', '넛지 디자인: 선택을 설계하는 기술'],
  readingStreak: 14,
  totalSaved: 47,
};

export const MOCK_PROFILE = {
  userId: 'demo-user',
  displayName: 'dots 사용자',
  bio: '깊이 있는 독서를 사랑합니다',
  avatar: null,
  joinedAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  stats: {
    savedArticles: 10,
    totalHighlights: 5,
  },
};
